### ISSUE TITLE
Allow the use of a forked repository

### ISSUE THREAD

**Issue by vincent-legoll** [Debian/dh-make-golang#100]
The use case: I want to create debian packaging for a project that is not compliant (which has imports not from github).

I forked this project to change the imports to be github-based, commited that in my fork and instructed dh-make-golang to use my fork.

Still got `imports .../...: unrecognized import path ".../..." (import path does not begin with hostname)` error messages.

Used strace to see that it downloaded from the upstream project.

I'm a total newcomer to go and its ecosystem, but this behavior looks strange...

**Comment by stapelberg** [comment]
Can you provide some steps to reproduce? I don’t quite understand what you’re doing and seeing.

**Comment by vincent-legoll** [comment]
I'm not sure it was a bug in dh-make-golang. I workarounded the pb and managed to get it to produce a packaging directory... So I'm closing it for now, I'll have to package other golang projects in the near future, I'll revisit the issue then.
