### ISSUE TITLE
Reorganize project and expose internals

### ISSUE THREAD

**Issue by Foxboron** [Debian/dh-make-golang#101]
This project has solved a lot of problems other linux distribution would need to solve to properly package golang. I'm curious if its beneficial to reorganize the project and expose the internals so it's easier to reuse the code. 

Any thoughts on this?

**Comment by stapelberg** [comment]
Which parts specifically would be interesting to you?

**Comment by Foxboron** [comment]
Everything from these seems usefull:
* `description.go`
* `estimate.go`
* `metadata.go`
* `progress.go`

And from `make.go`:
  * `upstream` struct
  * `debianNameFromGopkg`

I have plans to attempt package golang packages in Arch Linux the same way debian does it.

**Comment by stapelberg** [comment]
Okay. I’m not opposed to doing this, but have little time right now.

I would recommend:

1. copy the files into your project for the time being
2. report back once you have a working tool
3. report any changes you needed to make, if any (my gut feeling is that some changes might be needed)
4. we can clean up and expose the pieces of code you needed
5. you can remove the copied files and we can collaborate on any improvements going forward

Does that sound reasonable?

**Comment by Foxboron** [comment]
I think forking this project and working with it as a library is a better move. Easier to get an overview of the changes made and what could be merged back into the project.

Rest of it is completely reasonable and i'll gladly contribute the needed patches.
