### ISSUE TITLE
Put manual into project repository

### ISSUE THREAD

**Issue by Felixoid** [Debian/dh-make-golang#129]
Hello.

As far as I see, there's a manual in debian sources of the project http://httpredir.debian.org/debian/pool/main/d/dh-make-golang/dh-make-golang_0.3.1-1.debian.tar.xz `debian/man/dh-make-golang.md`

Could you put it into this repository, please?

**Comment by anthonyfok** [comment]
Good idea!  I'll do that now.  (Sorry for the late reply!)
