### ISSUE TITLE
Automatically create d/upstream/metadata

### ISSUE THREAD

**Issue by creekorful** [Debian/dh-make-golang#144]
Hello there!

I think it could be a good idea to create a simple [d/upstream/metadata](https://wiki.debian.org/debian/upstream) file when creating a package using dh-make-golang. 

Simple fields that can be found are: *Repository*, *Repository-Browse* and maybe more could be guess or just replaced with TODO so that the maintainer could easily find they are missing and set / remove them.

What do you think? I'm willing to do the PR of course.

Cheers,

**Comment by anthonyfok** [comment]
Hi @creekorful,

I totally agree with you.  At the very least, it will save Debian Janitor from a lot of extra work crawling through each Debian Go packages.  :laughing:
