### ISSUE TITLE
Unmet dependencies: golang-x-text-dev

### ISSUE THREAD

**Issue by TheFireMike** [Debian/dh-make-golang#155]
Hey,

I'm trying to build a package for our [Thola project](https://github.com/inexio/thola) using dh-make-golang. But after following the given instructions, the command `gbp buildpackage --git-pbuilder` fails with the following error:
```
Need to get 8491 kB/102 MB of archives. After unpacking 575 MB will be used.
The following packages have unmet dependencies:
 pbuilder-satisfydepends-dummy : Depends: golang-x-text-dev which is a virtual package and is not provided by any available package

Unable to resolve dependencies!  Giving up...
```
I'm quite unsure if the error is on my side or if it's in the program, so if anyone could help me there or guide me in the right direction that would be very nice!

**Comment by creekorful** [comment]
It should be golang-golang-x-test-dev. You should edit debian/control file to change it, and then it should build fine.

**Comment by TheFireMike** [comment]
Thank you very much, this indeed fixed the problem!
Unfortunately now I get another error while running `gbp buildpackage --git-pbuilder`:
```
Err http://deb.debian.org/debian sid/main amd64 golang-goprotobuf-dev amd64 1.3.4-2
  404  Not Found [IP: XXX]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/golang-goprotobuf/golang-goprotobuf-dev_1.3.4-2_amd64.deb: 404  Not Found [IP: XXX]
E: Unable to fetch some packages; try '-o APT::Get::Fix-Missing=true' to continue with missing packages
```
While debugging this I found out that this particular version isn't available, but I don't know how to advise the tool to use a newer/alternative version. This package is unfortunately not contained in the `debian/control` file, so I can't change the dependency there.
Do you have any advice how to fix or further debug this?

**Comment by creekorful** [comment]
You certainly need to update the git-pbuilder local cache. Can you try to run `git-pbuilder update` and try to build the package again?

**Comment by TheFireMike** [comment]
It works! Now the only problems left are related to Go modules which aren't packaged already.
Thank you for your help!

**Comment by creekorful** [comment]
You're welcome, have a good day :)
