### ISSUE TITLE
I'll apply the template you suggested here https://github.com/pytorch/pytorch/pull/56265#discussion_r615376640

### ISSUE THREAD

**Issue by Sifat1998** [Debian/dh-make-golang#160]
I'll apply the template you suggested here https://github.com/pytorch/pytorch/pull/56265#discussion_r615376640

__Originally posted by @Lezcano in https://github.com/pytorch/pytorch/pull/56265#discussion_r615892124__

**Comment by zhsj** [comment]
Seems off-topic.
