### ISSUE TITLE
Add go.step.sm to known hostnames

### ISSUE THREAD

**Issue by pymnh** [Debian/dh-make-golang#161]
I have recently packaged two packages with the import path go.step.sm. 

As you can see [here](https://ftp-master.debian.org/new/golang-step-crypto_0.9.0-1.html) and [here](https://ftp-master.debian.org/new/golang-step-cli-utils_0.4.1-1.html), Nilesh and I have agreed on using `step` resp.  `golang-step-$pkgname` as identifier. 

go.step.sm is not a general code hosting platform though (smallstep packages are still hosted on github) and future cases with this import path should be rare, but if you think it makes sense to include I'd do a PR

**Comment by zhsj** [comment]
could you send a pull request? Just like https://github.com/Debian/dh-make-golang/pull/126

**Comment by pymnh** [comment]
done -> #162
