### ISSUE TITLE
expired certificate

### ISSUE THREAD

**Issue by alteholz** [Debian/dh-make-golang#163]
Can someone please have a look at the certificate of pgt-api-server.debian.net? It seems to be expired today.

$ dh-make-golang create-salsa-project golang-gonum-v1-gonum
 2021/07/16 21:40:13 Post https://pgt-api-server.debian.net/v1/createrepo?repo=golang-gonum-v1-gonum: x509: certificate has expired or is not yet valid

**Comment by creekorful** [comment]
I think @stapelberg is the one who used to maintain the service but I'm not sure if it's still the case since he has take a step back from Debian.

**Comment by stapelberg** [comment]
Should now be fixed. Had to rebuild the pgt-api-server binary because LetsEncrypt turned down ACMEv1.

**Comment by creekorful** [comment]
Thanks a lot! 🎉
