### ISSUE TITLE
Implement `clone` command?

### ISSUE THREAD

**Issue by creekorful** [Debian/dh-make-golang#167]
I think it could be great to implement a clone command to dh-make-golang. It would work like this:

```
$ dh-make-golang clone golang-github-pkg-term
```

It would perform the following actions:

- (gbp or git)  clone "git@salsa.debian.org:go-team/packages/$1.git"
- apt source --tar-only "$1"

The motivations behind that are simple:

- It will make cloning a bit easier (only need the package name, not the whole URL)
- And most important: It will prevent uploads from being rejected in case of checksum mismatch, by forcing to use the .orig.tar.gz that comes from the archive.

What everyone think about that?

**Comment by creekorful** [comment]
@anthonyfok @zhsj what are your opinions on this?

**Comment by zhsj** [comment]
gbp actually supports `gbp clone vcsgit:golang-github-pkg-term`. On https://go-team.pages.debian.net/workflow-changes.html, the origin proposal is to set `postclone=origtargz` in gbp.conf.

**Comment by creekorful** [comment]
> gbp actually supports `gbp clone vcsgit:golang-github-pkg-term`. On https://go-team.pages.debian.net/workflow-changes.html, the origin proposal is to set `postclone=origtargz` in gbp.conf.

Uh thanks, I should have paid more attention to the documentation. 
I suppose adding the  postclone directly in our gbp.conf template (in dh-make-golang) won't work?

https://github.com/Debian/dh-make-golang/blob/97f4545313cab2d689c3e493d276332ab259873a/template.go#L292

**Comment by zhsj** [comment]
> I suppose adding the postclone directly in our gbp.conf template (in dh-make-golang) won't work?

It shold work for new package.

**Comment by creekorful** [comment]
> > I suppose adding the postclone directly in our gbp.conf template (in dh-make-golang) won't work?
> 
> It shold work for new package.

Didn't know if gbp do honor d/gbp.conf of the repository it is currently cloning, I'll try that way and will submit a PR if it works.
Thanks!

**Comment by creekorful** [comment]
> > I suppose adding the postclone directly in our gbp.conf template (in dh-make-golang) won't work?
> 
> It shold work for new package.

Eh. It doesn't work. from https://manpages.debian.org/testing/git-buildpackage/gbp-clone.1.en.html:

> Note that if you clone a repository that contains a hook configuration in debian/gbp.conf this hook will not be run automatically to prevent execution of untrusted code.

Does this clone command still make sense or should team member add postclone hook in their ~/gbp.conf?

**Comment by zhsj** [comment]
:disappointed: probably this is why it's never implemented although it's mentioned on the website.

I'm not sure what's the preferred way, the implementation for https://go-team.pages.debian.net/workflow-changes.html is in half-way for many years.

**Comment by creekorful** [comment]
> 😞 probably this is why it's never implemented although it's mentioned on the website.
> 
> I'm not sure what's the preferred way, the implementation for https://go-team.pages.debian.net/workflow-changes.html is in half-way for many years.

In the meantime, I have submitted the PR adding the clone command. Let's see what the others think about that!

**Comment by anthonyfok** [comment]
This is awesome @creekorful!  And thank you @zhsj for the `vcsgit:` tip!  I never knew that either!
Thank you both!

**Comment by zhsj** [comment]
The vcsgit tip is on https://go-team.pages.debian.net/packaging.html#_git_setup_for_automatically_authenticating

And also there is a config snip to rewrite https -> ssh for pushing.
