### ISSUE TITLE
Implement `check-depends` command

### ISSUE THREAD

**Issue by creekorful** [Debian/dh-make-golang#168]
When updating package to the latest upstream version, we need to check go.mod diff to determinate new / dropped dependencies, this step may be a bit optimized using a new  `check-depends` commands. It would work like this:

```
$ gbp import-orig --uscan # update to latest version
$ dh-make-golang  check-depends # from the package directory
+ non-needed dependencie(s): golang-github-pkg-term, golang-github-creekorful-mvnparser
+ missing dependencie(s): golang-github-antavelos-terminews
```

This could be quite helpful in this scenario.

**Comment by creekorful** [comment]
@anthonyfok @zhsj what are your opinions on this?

**Comment by zhsj** [comment]
I think dh-make-golang lacks an `update` feature for a long time... but yeah check-depends could be the first step.

**Comment by anthonyfok** [comment]
@creekorful This is awesome!  I've been doing that work manually, and did not think of having it done automatically, but it would be really nice!
A step further would be to modify debian/control automatically, and perhaps even read the version information from go.mod and add `(>= 0.9.1)` for example.  :-)
