### ISSUE TITLE
unexpected HTTP status code: got 500, want 200

### ISSUE THREAD

**Issue by Tachi107** [Debian/dh-make-golang#185]
Hi, whenever I try to use `dh-make-golang make` or `search` I get an error message mentioning a 500 HTTP status code.

    $ dh-make-golang search 'debi.*'                   
    2022/09/23 16:25:04 unexpected HTTP status code: got 500, want 200

This is my first time using `dh-make-golang`, so I may be doing something wrong.

**Comment by Tachi107** [comment]
It seems that this is happening because <https://api.ftp-master.debian.org/binary/by_metadata/Go-Import-Path> it not working:

    $ curl --dump-header - https://api.ftp-master.debian.org/binary/by_metadata/Go-Import-Path
    HTTP/2 500 
    x-content-type-options: nosniff
    x-frame-options: sameorigin
    referrer-policy: no-referrer
    x-xss-protection: 1
    permissions-policy: interest-cohort=()
    strict-transport-security: max-age=15552000
    access-control-allow-origin: *
    content-length: 786
    x-clacks-overhead: GNU Terry Pratchett
    content-type: text/html; charset=UTF-8
    date: Fri, 23 Sep 2022 15:04:35 GMT
    server: Apache
    
    
        <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
        <html>
            <head>
                <title>Error: 500 Internal Server Error</title>
                <style type="text/css">
                  html {background-color: #eee; font-family: sans;}
                  body {background-color: #fff; border: 1px solid #ddd;
                        padding: 15px; margin: 15px;}
                  pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
                </style>
            </head>
            <body>
                <h1>Error: 500 Internal Server Error</h1>
                <p>Sorry, the requested URL <tt>&#039;https://api.ftp-master.debian.org/binary/by_metadata/Go-Import-Path&#039;</tt>
                   caused an error:</p>
                <pre>Internal Server Error</pre>
            </body>
        </html>

**Comment by zhsj** [comment]
I think it is related to recent postgresql overload on ftp master server. Let's just be patient and wait ftp master to fix it.

**Comment by Tachi107** [comment]
Oh ok, I wasn't aware of that. While waiting for a reply in this thread, I reported this on the debian-dak list too, just in case: <https://lists.debian.org/debian-dak/2022/09/msg00013.html>

**Comment by Tachi107** [comment]
Yeah, according to 
<https://lists.debian.org/debian-dak/2022/09/msg00014.html> it seems 
something SQL related.
