### ISSUE TITLE
Consider handling the case where upstream created a lightweight version tag by mistake

### ISSUE THREAD

**Issue by anthonyfok** [Debian/dh-make-golang#22]
Nothing wrong with `dh-make-golang`, but in case issues like russross/blackfriday#196 turn out to be more common in the future, perhaps `dh-make-golang` could try to give a warning or workaround them too?  :-)

**Comment by stapelberg** [comment]
I think printing a warning when the most recent tag is lightweight, but the git repository also contains annotated tags, totally makes sense. Could you send a pull request which implements that please?

**Comment by anthonyfok** [comment]
Hello @stapelberg,

Sorry for the late reply.  I left this issue for quite some time, and finally worked on it about a month ago, but then got distracted and forgot to do the final testing and send a pull request.

Anyhow, I think I finally got a working patch in Pull Request #29.  Here are two GitHub repositories that I used for testing:

1. My outdated fork of russross/blackfriday.  This fork still contains the unannotated "v1.2" tag which Russ has since recreated as an annotated one:

    ```
$ dh-make-golang github.com/anthonyfok/blackfriday
2015/11/26 02:56:16 Downloading "github.com/anthonyfok/blackfriday/..."
2015/11/26 02:56:25 Determining upstream version number
2015/11/26 02:56:25 WARNING: Lightweight tag "v1.2" found, but the most recent annotated tag is "v1.1"
2015/11/26 02:56:25 Package version is "1.2+git20150112.36.7001890"
```

2. This is identical to the above, except I deleted the annotated tags "v1.0" and "v1.1" before pushing it to GitHub, leaving only one tag, the unannotated "v1.2" tag:

    ```
$ dh-make-golang github.com/anthonyfok/blackfriday-lightweight-tag
2015/11/26 03:04:15 Downloading "github.com/anthonyfok/blackfriday-lightweight-tag/..."
2015/11/26 03:04:34 Determining upstream version number
2015/11/26 03:04:34 INFO: Annotated tag not found, using lightweight tag "v1.2"
2015/11/26 03:04:34 Package version is "1.2+git20150112.36.7001890"
```

Cheers,
Anthony
