### ISSUE TITLE
please add me to this organization

### ISSUE THREAD

**Issue by ottok** [Debian/dh-make-golang#232]
### Your signed membership application

```plain text
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please add me (Debian user 'otto') to this organization
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEmbRSsR88dMO0U+RvvthEn87o2ogFAmdKeM4ACgkQvthEn87o
2ohxQxAAp6X+1D0JQBWTB/szJkpV7phFvNyhxPBKJN9vJyPPvtCJJvIFsVQmCJgw
3c1QOE4+diwXJdN2pMUCu6vp923UDZjUQhx6MvmjwL/dPPW1IbWL5n2hmod/BGny
WIMLhBSYQWlrD+nGunW5uhWqhqNjVS5asoQnZKDAH32cSu9cPfNfpiCo5oNUj0y6
1UjA7+Txi2UudsL2IAGpyMj0siTdRxzrGMVUIflzO9pWZWD3KzaL3Kbqj8kRtlRO
VtCI2gRG8nApijl0vZms4M00bxspp6Viep5XtGNmO5XhAoKW4p4VeBwzWwRIHPBN
Iesby7TgfhYhWs94K+ZUVyb72W0NxvuBRkFO7W4RrsdW7nAYgWpgQ38bjIOyjzTc
ekpWmgxn3c5SCdruEasyiQDHQgfBX3YdOTYTiT34rcrL9feJfPv+hAtERSaIx91D
ybyCNaJOjuJJthjdP2dqbGXW8CQ7pCDmUUcMCbFrNIi7EtXY7HtQP609OUTRfIzz
wnsdpr29kfNo88KoCxiRyCCK/6lM5Wv7+eU010PVNfKOmHINcpjCDiiLJYenSIsg
XAw1f1gIJ/9iWIqHGrmfhZ9KLGJ98/UWhEJYGd2x5TEcl7Z3dPz3HeioiNpp2lp8
z9voi3qH5VuhdFw0ZRGyPncjssKAvWiB7rA02uq4D9lMxklD8TY=
=zy1w
-----END PGP SIGNATURE-----
```

**Comment by umlaeute** [comment]
hmm, this is a quirk of the github issue template system.

For an organization/group, we can define issue templates. These generic templates are then visible for issues of the organization/group as a whole, but also for all the projects within the the organization.

In our case, we have an issue tempate "Join the Debian orga",  which is supposed to be used for join requests [for the **Debian** organization/group](https://github.com/Debian).
Unfortunately, the template bleeds through to the tracker of projects like `dh-make-golang`.

I do not know how we could possible "fix" this.

In any case:
- If you intend to join the *Debian* group, please head over to the [organization's ticket tracker](https://github.com/Debian/.github/issues/new/choose) and create a new ticket.
- If you intended to actually join the `dh-make-golang` team, then I think this ticket is the wrong course of action.


(I thought about closing this ticket, but as I'm actually unsure about both your intention and the policy of `dh-make-golang`, I leave that as an exercise to ... you)


 (like "Join the Debian group")

Tor the `Debian` organization, we can define issue templates. Unfortunately, this issue template is then visible for all the projects within the the organization.

**Comment by samueloph** [comment]
To add to umlaeute@'s comment, please apply for the organization instead @ottok, this way the automated job will pick it up, and I can add you to the "Debian Developers" team, which will give you admin access to this repo.

**Comment by ottok** [comment]
Thanks for the guidance. I filed now https://github.com/Debian/.github/issues/67 and closing this.
