### ISSUE TITLE
Implement the `${shlibs:Depends}` equivalent for Go packages

### ISSUE THREAD

**Issue by ottok** [Debian/dh-make-golang#233]
In C/C++ packages when programs compile with certain Build-Depends as defined in the debian/control file, the resulting run-time shared libraries are automatically added to the `${shlibs:Depends}` variable, which the binary deb packages depend on.

For example the [package Entr](https://salsa.debian.org/debian/entr) has:
```
Build-Depends:
 debhelper-compat (= 13),
 libbsd-dev,
 pkgconf,
```
and in the binary package:
```
Depends:
 ${misc:Depends},
 ${shlibs:Depends},
```

In Entr there is *no need* to manually add `libbsd0` as a run-time dependency.

In Go packages similar functionality is missing.

For example in the package `golang-github-charmbracelet-glamour` I needed to update the build dependency `golang-github-alecthomas-chroma-dev` -> `golang-github-alecthomas-chroma-v2-dev`. Initially, I did it only in `Build-Depends` and the package built, but wasn't usable by the other packages using it. To fix this I had to manually add the same dependency under `Depends` as well, which is annoying. These should just automatically update in tandem.

```
Source: golang-github-charmbracelet-glamour
Build-Depends:
               ...
               golang-github-alecthomas-chroma-v2-dev,
               golang-github-charmbracelet-lipgloss-dev,
               golang-github-charmbracelet-x-dev,
               ...

...
Package: golang-github-charmbracelet-glamour-dev
Architecture: all
Multi-Arch: foreign
Depends: 
         ...
         golang-github-alecthomas-chroma-v2-dev,
         golang-github-charmbracelet-lipgloss-dev,
         golang-github-charmbracelet-x-dev,
         ...
         ${misc:Depends}
```

**Comment by ottok** [comment]
See also related report in Debian: [Bug#822743: dh-golang: should assist in calculating -dev packages Depends:](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822743)

**Comment by zhsj** [comment]
Closing as this needs to be implemented in dh-golang, not dh-make-golang.
