### ISSUE TITLE
Invalid version number error

### ISSUE THREAD

**Issue by hxw** [Debian/dh-make-golang#31]
here is the start of the log:

```
2015/11/30 03:23:39 Downloading "github.com/cihub/seelog/..."
2015/11/30 03:23:42 Determining upstream version number
2015/11/30 03:23:42 Package version is "go1.1+git20151102.84.0f89bb7"
```

Further investigation shows that the author is tagging the "go compiler version" along with "vX.y" tags.
This library has two tags: `go1.1` and `v2.5`  both on the same commit.
Any Idea if it would be possible to pick the 2.5 from the other tag, though it might be easier to be able to specify a version as a command line argument.

**Comment by stapelberg** [comment]
What happens if you specify `-git_revision=v2.5` when running dh-make-golang?

**Comment by hxw** [comment]
I assumed that will checkout that tag rather than the head so will be missing the latest changes, so did not thing to try.  However this is the output:
~~~
2015/12/03 08:55:04 Downloading "github.com/cihub/seelog/..."
2015/12/03 08:55:08 Checking out git revision "v2.5"
2015/12/03 08:55:08 Determining upstream version number
2015/12/03 08:55:08 Package version is "go1.1"
2015/12/03 08:55:08 Determining package type
2015/12/03 08:55:08 Determining dependencies
~~~

the directory afterwards contains:
~~~
golang-github-cihub-seelog/
golang-github-cihub-seelog_go1.1.orig.tar.bz2
itp-golang-github-cihub-seelog.txt
~~~
Also changelog still contains the invalid version:
~~~
golang-github-cihub-seelog (go1.1-1) unstable; urgency=medium
~~~

**Comment by anthonyfok** [comment]
Perhaps adding a command-line option to allow the `--match` flag for `git describe`?

```
foka@debian:~/git/seelog$ git describe 
go1.1-84-g0f89bb7
foka@debian:~/git/seelog$ git describe --match v2.5
v2.5-84-g0f89bb7
```

**Comment by hxw** [comment]
It also accepts a glob
~~~
% git describe --match 'v*'
v2.5-83-g5841159
~~~
could even have a glob that forces a digit: `--match 'v[0-9]*'`

**Comment by stapelberg** [comment]
I like @anthonyfok’s idea. Pull requests which introduce a `-git_describe_match` flag are very welcome.

**Comment by hxw** [comment]
Ok, I'll have a try

**Comment by hxw** [comment]
Seems to work
~~~
% dh-make-golang -git_describe_match='v*' github.com/cihub/seelog 
2015/12/08 05:19:51 Downloading "github.com/cihub/seelog/..."
2015/12/08 05:19:55 Determining upstream version number
2015/12/08 05:19:55 Package version is "2.5-84-g0f89bb7"
2015/12/08 05:19:55 Determining package type
2015/12/08 05:19:55 Determining dependencies
~~~

**Comment by hxw** [comment]
The old request should be removed, and replaced by a much simpler one.

**Comment by stapelberg** [comment]
IIUC, this is done. Please reopen if I misunderstood, and explain what’s left to do.
