### ISSUE TITLE
-insecure flag

### ISSUE THREAD

**Issue by selam** [Debian/dh-make-golang#38]
Some repositorys dont use https, they only works for http so if we have a -insecure flag that will be nice

**Comment by stapelberg** [comment]
Which repository specifically? I’d prefer to see this fixed upstream. Setting up https is free and really simple these days with letsencrypt.org. Having an insecure way for software to make its way into Debian is not something I’d want to encourage.

**Comment by selam** [comment]
When i said "some repositories" I mean self hosted gitlab or similar softwares running inside of intranet.
Currently we run gitlab as self hosted in our intranet and i am sure there is another companies too.
We try to make our package for our distribution from our self hosted git repos. 

However, you'r right, any of insecure flag can not be encouraging in any part of OS distribution.

**Comment by stapelberg** [comment]
Thanks for clarifying. I feel that even for self-hosted solutions it makes sense to secure them behind TLS. If that’s not an option for whatever reason, perhaps carrying a patch for dh-make-golang in your intranet makes the most sense.
