### ISSUE TITLE
Switch from "tar --exclude-vcs" to "git archive" to keep .gitignore

### ISSUE THREAD

**Issue by anthonyfok** [Debian/dh-make-golang#41]
After running into trouble on several occasions trying to upgrade `golang-*-dev` packages that predate `dh-make-golang`, especially error merging with deleted `.gitignore` in `dh-make-golang`-generated tarball, I become convinced that the use of `tar --exclude-vcs`, which indiscriminately delete files like `.gitignore`, is not the best solution.

Would `git archive` be a better solution?  Perhaps something like the following?

```
git archive --format=tar --prefix=golang-github-author-package/ upstream/0.0_git20160429.0.9abcdef \
    | xz -9 >golang-github-author-pacakage_0.0~git20160429.0.9abcdef.orig.tar.xz
```

Cheers,
Anthony

**Comment by stapelberg** [comment]
Can you point me to a couple of examples in which the `tar` calls leads to problems?

**Comment by anthonyfok** [comment]
I can't remember the names of the packages off the top of my head, but trouble arises during an upstream version upgrade in the following situation:

1. Upstream author originally created a `.gitignore` file...
2. ...which got removed indiscriminately by dh-make-golang's use of `tar --exclude-vcs` when it creates an `.orig.tar.gz` after a `git clone`.
3. The first Debian package maintainer decided to create his/own `.gitignore` file during packaging.
4. A new upstream release is available as a tarball, say `v1.0.0.tar.gz`.
5. A pkg-go team member decides to package the new version using `v1.0.0.tar.gz` as pristine-tar by running something like `gbp import-orig --uscan`.
6. Wham!  Big messy merge conflict!

But messy merge conflict situation aside, I believe the intention to use `tar --exclude-vcs` is to remove the `.git/` directory, which has no place in a release tarball.  However, `.gitignore` should have been kept as is, especially when the upstream release tarballs contains it, and thus _`dh-make-golang` should not remove it._

**Comment by stapelberg** [comment]
Thanks for providing more detail. I’m afraid that I don’t have the time to identify an example myself. Can you provide me with an example with which this problem occurs please?

**Comment by zhsj** [comment]
@stapelberg take this for example, https://github.com/hashicorp/atlas-go
Test fixtures like https://github.com/hashicorp/atlas-go/tree/master/archive/test-fixtures/archive-hg/.hg will be excluded if you use `tar --exclude-vcs`
