### ISSUE TITLE
Cannot derive Debian package name: unknown hoster "cloud.google.com"

### ISSUE THREAD

**Issue by anthonyfok** [Debian/dh-make-golang#49]
While I was trying to update the `golang-google-cloud` Debian package, I noticed that Google has recently changed the import path from `google.golang.org/cloud` to `cloud.google.com/go`.

I then attempted to fetch the latest version as a tarball using `dh-make-golang cloud.google.com/go`, but was greeted with this error:

    Cannot derive Debian package name: unknown hoster "cloud.google.com".
    See -help output for -allow_unknown_hoster

Thanks!

**Comment by stapelberg** [comment]
Please submit a pull request to add the hoster to https://github.com/Debian/dh-make-golang/blob/master/make.go#L330

Until that pull request is merged, you can use `-allow_unknown_hoster`, as the error message suggests.

**Comment by anthonyfok** [comment]
Thank you for your reply.  However, the reason that I sent an Issue rather than a Pull Request in the first place, was that I do not know what to name the "cloud.google.com" hoster.  The name `google` is already taken, and using just `cloud` doesn't seem appropriate either.  Should it be `googlecloud` or `cloudgoogle` or `cloud.google` or `cloud-google` or whatnot?  I think you, as the original author of `dh-make-golang`, are way more qualified than I am to make that decision.

So, please just go ahead and make the change yourself, at your convenience.  Thank you1
