### ISSUE TITLE
gbp:error: Failed to commit tree:  *** Please tell me who you are.

### ISSUE THREAD

**Issue by techtonik** [Debian/dh-make-golang#52]
```
$ dh-make-golang -allow_unknown_hoster github.com/zyedidia/micro 
...
gbp:error: Failed to commit tree: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

Is it possible to run it without writing global config? Thanks.

**Comment by techtonik** [comment]
I believe the problem is this line - https://github.com/Debian/dh-make-golang/blob/71f5e23f27a23baa4018d2aebae05360e323431a/make.go#L316

Is it possible to catch the error and commit this line under some different name (or don't commit), so that I can later configure local params for this repo?

**Comment by stapelberg** [comment]
Can you explain the use-case for this? Usually, I’d expect people to set the `DEBEMAIL` and `DEBFULLNAME` environment variables (for Debian Developers/Maintainers) or at least their git configuration.

**Comment by techtonik** [comment]
I just wanted to check if `micro` compiles on Debian, to see if I can package and install latest version from GitHub for troubleshooting. As I am not a Debian developer/maintainer, I don't have those `DEB*` credentials (and didn't know about them).

I also do this inside container environment, and setting up `git` for committing there is tedious for every project.

**Comment by stapelberg** [comment]
Thanks for clarifying.

I’ll have to reject this feature request, as the tool is first and foremost targeted at debian developers. I think when trying to (re)build packages, it’s fair to require a development setup, which in this case includes git setup or the DEB* environment variables.

Failing early is the preferred failure mode (instead of, for example, putting in “nobody” as user name, which you’d only discover later on if at all).

**Comment by techtonik** [comment]
It is fair to require development setup when you're trying to commit stuff, but testing it should go in read only mode. Seeing that this tool wants to commit something fails this smoke test. I wouldn't risk giving it my credentials in production as it seems too capable.

**Comment by techtonik** [comment]
What I really wanted to say is that having a focus on Debian users helps with onboarding them as debian developers someday (if you need more developers, of course). =)

**Comment by stapelberg** [comment]
dh-make-golang uses a local git working copy. A git commit is a local operation, not be confused with a push. There are no credentials required. DEBFULLNAME and DEBEMAIL are plain text strings, no credentials.

**Comment by techtonik** [comment]
Yes, but users don't know that.

**Comment by techtonik** [comment]
At least this info can be added to error message.

**Comment by stapelberg** [comment]
I agree that error messages should be as friendly and helpful as possible.

I tried reproducing the issue in order to see how we could improve the error message, but I fail to reproduce it:

```
$ docker run -t -i debian:sid /bin/bash

root# apt update && apt install git-buildpackage dh-make-golang

root# dh-make-golang -allow_unknown_hoster github.com/zyedidia/micro
2017/03/23 08:56:13 Downloading "github.com/zyedidia/micro/..."
2017/03/23 08:56:32 Determining upstream version number
2017/03/23 08:56:32 WARNING: Annotated tag not found, using lightweight tag "nightly"
2017/03/23 08:56:32     Lightweight tags (created by e.g. "git tag nightly"
2017/03/23 08:56:32     with no flag) are problematic because, among other
2017/03/23 08:56:32     things, they are ignored by "git describe" by default.
2017/03/23 08:56:32     Please suggest that the upstream replaces the
2017/03/23 08:56:32     lightweight tags with annotated ones.  See
2017/03/23 08:56:32     https://github.com/russross/blackfriday/issues/196
2017/03/23 08:56:32     for details.
2017/03/23 08:56:32 
2017/03/23 08:56:32 Package version is "nightly+git20170311.0.53a19af"
2017/03/23 08:56:32 Determining package type
2017/03/23 08:56:32 Assuming you are packaging a program (because "github.com/zyedidia/micro/cmd/micro" defines a main package), use -type to override
2017/03/23 08:56:32 Determining dependencies
2017/03/23 08:56:32 WARNING: Using "layeh" as canonical hostname for "layeh.com". If that is not okay, please file a bug against dh-make-golang.
2017/03/23 08:56:34 Build-Dependency "golang-github-go-errors-errors-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-github-zyedidia-clipboard-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-github-zyedidia-glob-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-github-zyedidia-json5-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-layeh-gopher-luar-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-github-yuin-gopher-lua-dev" is not yet available in Debian
2017/03/23 08:56:34 Build-Dependency "golang-github-zyedidia-tcell-dev" is not yet available in Debian
2017/03/23 08:56:36 
2017/03/23 08:56:36 Packaging successfully created in /usr/src/micro
2017/03/23 08:56:36 
2017/03/23 08:56:36 Resolve all TODOs in itp-micro.txt, then email it out:
2017/03/23 08:56:36     sendmail -t < itp-micro.txt
2017/03/23 08:56:36 
2017/03/23 08:56:36 Resolve all the TODOs in debian/, find them using:
2017/03/23 08:56:36     grep -r TODO debian
2017/03/23 08:56:36 
2017/03/23 08:56:36 To build the package, commit the packaging and use gbp buildpackage:
2017/03/23 08:56:36     git add debian && git commit -a -m 'Initial packaging'
2017/03/23 08:56:36     gbp buildpackage --git-pbuilder
2017/03/23 08:56:36 
2017/03/23 08:56:36 To create the packaging git repository on alioth, use:
2017/03/23 08:56:36     ssh git.debian.org "/git/pkg-go/setup-repository micro 'Packaging for micro'"
2017/03/23 08:56:36 
2017/03/23 08:56:36 Once you are happy with your packaging, push it to alioth using:
2017/03/23 08:56:36     git push git+ssh://git.debian.org/git/pkg-go/packages/micro.git --tags master pristine-tar upstream

root# cd micro

root# git log
commit 9b5a32c9b15a129a373006fec289af8fd03b1c7f
Author: root <root@886c7f97b923>
[…]
```

**Comment by techtonik** [comment]
I can't repeat it myself, so it seems resolved. Thanks. =)
