### ISSUE TITLE
dh-make-golang not including vendor dependencies in debian/control ?

### ISSUE THREAD

**Issue by Baisang** [Debian/dh-make-golang#55]
When I run `dh-make-golang github.com/quilt/quilt`, it seems to not include the dependencies I have imported into my project using `govendor` in my `debian/control` file. I'm new to packaging golang into debian applications, especially those that have dependencies, so I'm not sure what this is supposed to do.

From reading https://github.com/Debian/dh-make-golang/issues/46, that these dependencies should be listed in `debian/control`, but currently they aren't for me. So when I do try to use `gbp` to build my package I get an error for all of my dependencies saying it can't find them in my `$GOROOT` or `$GOPATH`.

I am running version 0.0~git20161120.0.71f5e23-1 (2016-11-20), and the commands I have done are the following:

`dh-make-golang github.com/quilt/quilt`

Creates the `debian` folder and associated files with TODOs, which I correct. But I noticed here the relevant parts of my `debian/rules` look like:

```
Source: quilt
Section: devel
Priority: extra
Maintainer: Brian Sang <sang.bri@gmail.com>
Uploaders: Brian Sang <sang.bri@gmail.com>
Build-Depends: debhelper (>= 10),
               dh-golang,
               golang-any
Standards-Version: 3.9.8
Homepage: https://github.com/quilt/quilt
Vcs-Browser: https://github.com/quilt/quilt.git
Vcs-Git: https://github.com/quilt/quilt.git
XS-Go-Import-Path: github.com/quilt/quilt

Package: quilt
Architecture: any
Built-Using: ${misc:Built-Using}
Depends: ${shlibs:Depends},
         ${misc:Depends}
Description: Quilt
```

and then when I try to build using `gbp buildpackage`, it goes until it hits the golang dependencies:

```
src/github.com/quilt/quilt/quilt.go:17:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/go-1.7/src/github.com/Sirupsen/logrus (from $GOROOT)
	/build/quilt-0.0+git20170328.741.b2136f2/obj-x86_64-linux-gnu/src/github.com/Sirupsen/logrus (from $GOPATH)
 .............
```

And this happens for each dependency. So I'm not sure if `dh-make-golang` is supposed to sort all of this out for me, or if I have to manually do this somehow. Any help would be appreciated!

**Comment by stapelberg** [comment]
Thanks for the detailed report. Re-reading this issue and #46 in detail, I realized that I now better understand what they’re about, and that they are indeed the same problem. Let’s continue the discussion in #46 — sorry for the detour.
