### ISSUE TITLE
Error: 'can't load package: package .: no buildable Go source files in'

### ISSUE THREAD

**Issue by Commenter123** [Debian/dh-make-golang#56]
```
$ cd $(mktemp -d)
$ dh-make-golang github.com/agl/ed25519
$ cd golang-github-agl-ed25519/
$ git add -A
$ git commit -m "Initial packaging"
$ gbp buildpackage
...
dh build --buildsystem=golang --with=golang
   dh_testdir -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   dh_auto_build -O--buildsystem=golang
warning: "/..." matched no packages
can't load package: package .: no buildable Go source files in /tmp/rnd-dir/golang-github-agl-ed25519/obj-x86_64-linux-gnu
dh_auto_build: go install -v returned exit code 1
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
gbp:error: 'debuild -i -I' failed: it exited with 29
```

It tries to match `/...` instead of `./...` (leading period sign)

**Comment by stapelberg** [comment]
I can’t reproduce this. Which version of dh-make-golang are you using? Try installing from git please. If that doesn’t help, can you also provide the git repository which dh-make-golang created on your machine please?

**Comment by Commenter123** [comment]
Hi @stapelberg,

all packages are installed from Debian stable.

- dh-golang 1.6
- dh-make-golang c9d2a26033d7c8c469aaa4188cfba5d8c69b54a5 (current master)

The only thing I did was to replace the debhelper dependency on v10 to v9 (in control and compat)

```sh
$ git clone https://github.com/agl/ed25519 ../ed25519-git
$ diff -r --exclude=.git . ../ed25519-git/
Only in .: debian
Only in .: .gitignore
Only in .: obj-x86_64-linux-gnu
```

```sh
$ find obj-x86_64-linux-gnu/
obj-x86_64-linux-gnu/
obj-x86_64-linux-gnu/src
obj-x86_64-linux-gnu/src/golang.org
obj-x86_64-linux-gnu/src/ed25519_test.go
obj-x86_64-linux-gnu/src/extra25519
obj-x86_64-linux-gnu/src/extra25519/extra25519_test.go
obj-x86_64-linux-gnu/src/extra25519/extra25519.go
obj-x86_64-linux-gnu/src/code.google.com
obj-x86_64-linux-gnu/src/edwards25519
obj-x86_64-linux-gnu/src/edwards25519/edwards25519.go
obj-x86_64-linux-gnu/src/edwards25519/const.go
obj-x86_64-linux-gnu/src/ed25519.go
```

Is there anything else you need?

**Comment by stapelberg** [comment]
> Is there anything else you need?

Can you please just provide the entire output of dh-make-golang (i.e. a git repo, or an attached tarball)? I’d like to see if the output differs between my machine and your machine.

**Comment by Commenter123** [comment]
Heres the git bundle: [my-repo.bundle.zip](https://github.com/Debian/dh-make-golang/files/1012430/my-repo.bundle.zip)

```sh
$ unzip my-repo.bundle.zip # Sorry github allows only zips
$ git clone my-repo.bundle
$ cd my-repo
```

**Comment by Commenter123** [comment]
ok, `gbp buildpackage --git-pbuilder` worked. but why does it not work without the `--git-pbuilder`? Different package versions?

**Comment by stapelberg** [comment]
Thanks for the update. I’m not sure why it requires pbuilder on your machine, I use Debian testing or unstable for development.

I’ll close this issue as there’s no bug in dh-make-golang; the expected environment is to use sbuild or pbuilder.

**Comment by Commenter123** [comment]
@stapelberg thanks for this awesome tool and sorry for wasting your time. Have a nice evening.
