### ISSUE TITLE
Overaggressive pruning (and no configurability)

### ISSUE THREAD

**Issue by tianon** [Debian/dh-make-golang#7]
I'm trying to use `dh-make-golang` to package https://getgb.io, but I'm running into trouble right off because https://github.com/constabulary/gb/tree/933576cf5c8367145d3bae615558bac89fda415a/vendor is `github.com/constabulary/gb/vendor`, but it gets `--exclude` in the tar invocation, so the orig tarball doesn't have this package.

My thought for solving this is if the `vendor` directory exists, let's check if there are `*.go` files directly inside.  If there aren't, we add `--exclude`, otherwise we leave it in (because it must be a legitimate package).  Another way to check for this could be to just do something like `go list <gopkg>/vendor` and see if it comes back with itself or if it says that's not a valid package.

For example:

``` console
$ go list github.com/docker/docker/vendor
can't load package: package github.com/docker/docker/vendor: no buildable Go source files in GOPATH/src/github.com/docker/docker/vendor
```

Versus:

``` console
$ go list github.com/constabulary/gb/vendor
github.com/constabulary/gb/vendor
```

**Comment by tianon** [comment]
(I'm happy to work on a patch if we agree on the solution, but I'd rather not spend the effort until we come to a conclusion. :+1:)

**Comment by stapelberg** [comment]
From https://go-review.googlesource.com/#/c/10923/:

> The short form must always be used: no import path can contain “/vendor/” explicitly.

Maybe I’m interpreting this wrong, but won’t that mean that any source which imports gb/vendor will/might? break when GO15VENDOREXPERIMENT=1 is set?

If that’s accurate, it strikes me as a bad idea to name a package “vendor”. I think we should clarify this point first before making a decision. Ideally, I’d love to see a statement by upstream (maybe on golang-nuts?) to clarify this point.

**Comment by tianon** [comment]
Good point -- I'll test against Go 1.5 with the experimental env set and report back.  If it fails, I'll be poking upstream about the name choice. :+1:

**Comment by tianon** [comment]
```console
$ go version
go version go1.5beta3 linux/amd64
$ env | grep GO15VENDOREXPERIMENT
GO15VENDOREXPERIMENT=1
```

`github.com/constabulary/gb` downloads and compiles successfully, so I think it's not explicitly rejected in the upstream implementation.  Perhaps only subpackages of `/vendor` are?

**Comment by tianon** [comment]
https://github.com/golang/go/commit/45971c60c31303ed9100d3ac8c3030c4d48d7084 looks related though -- I'll try to get something more recent than `beta3` spun up for testing

**Comment by tianon** [comment]
Even against tip, it still works. :disappointed:

```console
$ go version
go version devel +be39a42 Tue Aug 4 18:54:56 2015 +0000 linux/amd64
$ export GO15VENDOREXPERIMENT=1
$ go get -v github.com/constabulary/gb/...
github.com/constabulary/gb (download)
github.com/constabulary/gb
github.com/constabulary/gb/cmd
github.com/constabulary/gb/vendor
github.com/constabulary/gb/cmd/gb
github.com/constabulary/gb/cmd/gb-vendor
```

**Comment by tianon** [comment]
Upstream changed that package name, so this is not a problem for me. :+1:
