### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by davidsnt** [Debian/dh-make-golang#72]
I have a standalone golang application, that uses github.com/golang/glog

My directory structure is something like,

$GOPATH/godebian
- pkg/
- bin/
- src/
     github.com/
     goDebian.go

upon running dh-make-golang, I see the following error.

> $ dh-make-golang -allow_unknown_hoster /home/godebian
> panic: runtime error: slice bounds out of range
> 
> goroutine 1 [running]:
> panic(0x7ec2c0, 0xc82000e0e0)
> 	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
> main.debianNameFromGopkg(0x7ffc63901209, 0x18, 0x868190, 0x7, 0x0, 0x0)
> 	/build/dh-make-golang-OhS4Fp/dh-make-golang-0.0~git20150913.0.1221041/
> obj-x86_64-linux-gnu/src/github.com/Debian/dh-make-golang/make.go:307 +0x829
> main.main()
> /build/dh-make-golang-OhS4Fp/dh-make-golang-0.0~git20150913.0.1221041/
> obj-x86_64-linux-gnu/src/github.com/Debian/dh-make-golang/make.go:575 +0x65e
>

**Comment by stapelberg** [comment]
The error handling is obviously an issue which we should fix, but note that you should call dh-make-golang on a Go package name (`go get <arg>` needs to work), e.g. `dh-make-golang github.com/Debian/pk4`
