### ISSUE TITLE
Bug: dependencies for vendored repo

### ISSUE THREAD

**Issue by MOZGIII** [Debian/dh-make-golang#78]
I have an app vendored with the official golang's `dep` (https://github.com/golang/dep) utility. I should not require any external dependencies.
However, when I use `dh-make-golang` it adds `golang-golang-x-crypto-dev` as a `Build-Depends`. I suppose something's wrong.
Should I just manually remove `golang-golang-x-crypto-dev` for now?

**Comment by stapelberg** [comment]
Nothing is wrong — Debian doesn’t do vendored dependencies as a general policy, regardless of the language. When packaging a Go program for Debian, we un-vendor all dependencies.

**Comment by MOZGIII** [comment]
Wow. Is it possible to do correctly? Vendored versions and versions in the repo may not match exactly - and this might break the code. Plus, why is there only one dependency there (should be more)? Are not all of them unvendored?
Sorry for the questions, I'm just trying to understand. I'm trying to deliver reproducible builds with my packages, and it seems like with debian this task starts to be non-local towards the source tree I provide and the go version.

**Comment by stapelberg** [comment]
> Wow. Is it possible to do correctly? Vendored versions and versions in the repo may not match exactly - and this might break the code.

So far, we have only seen compilation errors when this happens, which are usually easy to fix.

> Plus, why is there only one dependency there (should be more)? Are not all of them unvendored?

Can you share the command line you used, so that I can try to reproduce the problem?

> Sorry for the questions, I'm just trying to understand. I'm trying to deliver reproducible builds with my packages, and it seems like with debian this task starts to be non-local towards the source tree I provide and the go version.

If the Go compiler version matches, and when using vendoring, Go builds should be reproducible on any Linux distribution. Can you elaborate on what you need on top of that?
