### ISSUE TITLE
Also remove vendor/ directory from subdirectories

### ISSUE THREAD

**Issue by stapelberg** [Debian/dh-make-golang#87]
E.g. github.com/zyedidia/micro is affected

**Comment by rajudev** [comment]
when can we expect the updated `dh-make-golang` to make it to unstable?

**Comment by stapelberg** [comment]
I can package a new snapshot once I’m done with my other commits. For the time being, just use “go get -u github.com/Debian/dh-make-golang” and run ~/go/bin/dh-make-golang. It’s quick & painless :)

**Comment by rajudev** [comment]
Thanks for the steps. I am new to `Go` as well. Those steps will help
