### ISSUE TITLE
Working with dep

### ISSUE THREAD

**Issue by immesys** [Debian/dh-make-golang#92]
I am trying to build a package for a program that uses dep. The repository does not contain the vendor directory but requires the user to run `dep ensure` before building. Where would be the right place to add support for this in dh-make-golang? (checking for Godep lock file, running dep ensure).

**Comment by stapelberg** [comment]
It’s not clear to me that we should add support for this.

Why does upstream require users to run dep ensure? What happens if you just go ahead with dh-make-golang as-is?

**Comment by immesys** [comment]
Well dep ensure populates the vendor directory with specific commits of dependencies. If we don't do that then we would presumably fulfill dependencies by using packaged libraries? I am very new to this so its not clear to me when an external library (via another debian package and build dependency) should be used rather than a vendored dependency.

**Comment by stapelberg** [comment]
Yeah, we drop vendor/ directories in Debian when packaging, and we use the packaged versions of the libraries (not at a specific commit).

I’ll close this issue since running dep wouldn’t help us — it would create a vendor directory which we would then immediately discard.
